### PR TITLE
Fix default_unit_label_dict for aqi and aqi_color

### PR DESCRIPTION
**Pull request by ArendPWS**
Encountered this when trying to implement readings in Belchertown skin.

### CODE REVIEW

**Comment by chaunceygardiner** [comment]
Hi,

Can you detail what you encountered so that I can reproduce and verify this change fixes it?

**Comment by ArendPWS** [comment]
Another user of the Belchertown skin opened an issue about getting the correct readings (with MQTT support) from weewx-airlink into the skin. This is the topic:

https://github.com/poblabs/weewx-belchertown/issues/648

The user confirms everything is working now. To get it fixed I followed these instructions from

[http://www.weewx.com/docs/customizing.htm#Creating_a_new_unit_group](http://www.weewx.com/docs/customizing.htm#Creating_a_new_unit_group)

This is how a unit label (assigned to a unit) is added to the default_unit_label_dict.

**Comment by chaunceygardiner** [comment]
At first glance, it looks like this PR removes the labels for pm2_5_aqi, etc. that this extension writes to loop packets and adds labels for aqi and aqi_color that this extension does not write.

I’m happy to to shown that I got this wrong; but, if this is indeed the case, whatever code that is changing pm2_5_aqi to aqi (and the same for aqi_color) should add these labels (or they could be added in weewx.conf).

**Comment by ArendPWS** [comment]
I must admit it also took me some time to figure out what went wrong with your code. But once you see it, it's obvious: you applied the observation names instead of the unit names in "default_unit_label_dict". If you want to see a working example with all fixes you can check the site of the user who reported the issues (his site is also mentioned in the Belchertown issue):

[http://www.gricewoodsweather.com/](http://www.gricewoodsweather.com/)

There is nothing more I can add to this. I don't own a Davis Airlink, but it was fun getting it's output into Belchertown. :wink:

**Comment by chaunceygardiner** [comment]
> There is nothing more I can add to this. I don't own a Davis Airlink
I was looking for what expression(s) wasn’t working; but it is somewhat obvious.  I’ve reproduced that $unit.label.pm2_5_aqi, $unit.label.pm2_5_aqi_color, etc. do not work.

I’ll merge this PR.  Thanks for sending it.

**Pull request merged**
